/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ILightGBMJava */

#ifndef _Included_ILightGBMJava
#define _Included_ILightGBMJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ILightGBMJava
 * Method:    createDatasetFromFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;LDatesetHandle;)LDatesetHandle;
 */
JNIEXPORT jobject JNICALL Java_ILightGBMJava_createDatasetFromFile
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     ILightGBMJava
 * Method:    getLastError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ILightGBMJava_getLastError
  (JNIEnv *, jobject);

/*
 * Class:     ILightGBMJava
 * Method:    datasetFree
 * Signature: (LDatesetHandle;)I
 */
JNIEXPORT jint JNICALL Java_ILightGBMJava_datasetFree
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ILightGBMJava
 * Method:    datasetSaveBinary
 * Signature: (LDatesetHandle;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ILightGBMJava_datasetSaveBinary
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     ILightGBMJava
 * Method:    datasetGetNumData
 * Signature: (LDatesetHandle;)J
 */
JNIEXPORT jlong JNICALL Java_ILightGBMJava_datasetGetNumData
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ILightGBMJava
 * Method:    datasetGetNumFeature
 * Signature: (LDatesetHandle;)J
 */
JNIEXPORT jlong JNICALL Java_ILightGBMJava_datasetGetNumFeature
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ILightGBMJava
 * Method:    createBooster
 * Signature: (LDatesetHandle;Ljava/lang/String;)LBooster;
 */
JNIEXPORT jobject JNICALL Java_ILightGBMJava_createBooster
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     ILightGBMJava
 * Method:    createBoosterFromModelFile
 * Signature: (Ljava/lang/String;J)LBooster;
 */
JNIEXPORT jobject JNICALL Java_ILightGBMJava_createBoosterFromModelFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ILightGBMJava
 * Method:    predictBoosterForMat
 * Signature: (LBooster;[FIIZJ)[F
 */
JNIEXPORT jfloatArray JNICALL Java_ILightGBMJava_predictBoosterForMat
  (JNIEnv *, jobject, jobject, jfloatArray, jint, jint, jboolean, jlong);

#ifdef __cplusplus
}
#endif
#endif
